---
title: "CARET package"
author: "Ale F. Benages"
date: "3/26/2021"
output: html_document
---

## Example 0
fit a model to the mtcars data
```{r}
rm(list = ls()) # clean and remove all the values of the environment
```


```{r}
data("mtcars")
model <- lm(mpg ~ hp, mtcars[1:20, ])  
```


predct in sample
```{r}
predicted <- predict(model, mtcars[1:20, ], type = 'response')
```

calculate RMSE
```{r}
actual <- mtcars[1:20, 'mpg']
sqrt(mean((predicted - actual) ^2))
```




# Ex.1 -  WholeYear Example

```{r}
rm(list = ls()) # clean and remove all the values of the environment
```


```{r}
#caret model - Automatic Tuning Grid
#http://topepo.github.io/caret/bytag.html
#model training: http://topepo.github.io/caret/training.html
#model measurement: http://topepo.github.io/caret/other.html
#dataframe = WholeYear
#Y Value = SolarRad

df <- read.csv('WholeYear.csv')
df[1:5, ]
```


```{r}
summary(df)
```

```{r}
#load library and set seed
library(caret)
library(tictoc)
set.seed(9982)
```

```{r}
# to reduce CPU usage we create a small data set with 20% of the data
WholeYear <- df[sample(1:nrow(df), 7000,replace=FALSE),]
dim(WholeYear) # dimension of the sample
dim(df) # dimension of the full dataset
```

```{r}
# define an 75%/25% train/test split of the dataset
tic()
inTraining <- createDataPartition(WholeYear$SolarRad, p = .75, list = FALSE)
training <- WholeYear[inTraining,]
testing <- WholeYear[-inTraining,]

dim(training)
dim(testing)
toc()
```

```{r}
#10 fold cross validation
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 1)
```

```{r}
#train Random Forest Regression model with a tuneLenght = 1 (trains with 1 mtry value for RandomForest)
tic()
rfFit1 <- train(SolarRad~., data = training, method = "rf", trControl=fitControl, tuneLength = 1)
toc()
```

```{r}
#training results
tic()
rfFit1
toc()
```




# Ex. 2 

```{r}
rm(list = ls()) # clean and remove all the values of the environment
```


```{r}
#caret model - Automatic Tuning Grid
#http://topepo.github.io/caret/bytag.html
#model training: http://topepo.github.io/caret/training.html
#model measurement: http://topepo.github.io/caret/other.html
#dataframe = WholeYear
#Y Value = SolarRad

#load library and set seed
library(caret)
set.seed(998)

# lead the data
df <- read.csv('WholeYear.csv')

#create a 20% sample of the data
WholeYear <- df[sample(1:nrow(df), 7000,replace=FALSE),]

# define an 75%/25% train/test split of the dataset
inTraining <- createDataPartition(WholeYear$SolarRad, p = .75, list = FALSE)
training <- WholeYear[inTraining,]
testing <- WholeYear[-inTraining,]
```

```{r}
#10 fold cross validation
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 1)
```


```{r}
#train Linear Regression model with a tuneLenght = 2 (trains with 2 mtry values for RandomForest)
rfFit2 <- train(SolarRad~., data = training, method = "rf", trControl=fitControl, tuneLength = 2)
```


```{r}
#training results
rfFit2
```






